---
- name: create admin group
  group:
    name: admin
    state: present

- name: passwordless sudo
  lineinfile:
    dest: /etc/sudoers.d/010_admin
    state: present
    line: "%admin ALL=(ALL:ALL) NOPASSWD:ALL"
    create: yes

- name: create personal user account
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    append: yes
  loop: "{{ users }}"
  when:
    - not ansible_check_mode

- name: insert personal ssh key in authorized
  authorized_key:
    user: "{{ item.name }}"
    state: present
    exclusive: yes
    key: "{{ item.ssh_pub |join('\n') }}"
  loop: "{{ users }}"
